// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NatsStreamingCluster) DeepCopyInto(out *NatsStreamingCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NatsStreamingCluster.
func (in *NatsStreamingCluster) DeepCopy() *NatsStreamingCluster {
	if in == nil {
		return nil
	}
	out := new(NatsStreamingCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NatsStreamingCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NatsStreamingClusterList) DeepCopyInto(out *NatsStreamingClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NatsStreamingCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NatsStreamingClusterList.
func (in *NatsStreamingClusterList) DeepCopy() *NatsStreamingClusterList {
	if in == nil {
		return nil
	}
	out := new(NatsStreamingClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NatsStreamingClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NatsStreamingClusterSpec) DeepCopyInto(out *NatsStreamingClusterSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NatsStreamingClusterSpec.
func (in *NatsStreamingClusterSpec) DeepCopy() *NatsStreamingClusterSpec {
	if in == nil {
		return nil
	}
	out := new(NatsStreamingClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NatsStreamingClusterStatus) DeepCopyInto(out *NatsStreamingClusterStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NatsStreamingClusterStatus.
func (in *NatsStreamingClusterStatus) DeepCopy() *NatsStreamingClusterStatus {
	if in == nil {
		return nil
	}
	out := new(NatsStreamingClusterStatus)
	in.DeepCopyInto(out)
	return out
}
